### PR TITLE
Improving Jenkinsfile regarding PyKeOps to run tests in dedicated Python environments

### PR DESCRIPTION
**Pull request by gdurif**
Objective

- [x] run each step in a dedicated Python environment for PyKeOps
- [x] local install of requirements through pip
- [x] run CI test through slurm scheduler on oban GPU machine

Note (2022/03/14): WIP, not ready to merge (`Jenkinsfile` is being improved by steps)

### CODE REVIEW

**Comment by gdurif** [comment]
@bcharlier @joanglaunes  I am trying to improve the [test setup](https://github.com/getkeops/keops/blob/improve_ci_setup/Jenkinsfile) (through specific `extra_requires` in [`pykeops/setup.py`](https://github.com/getkeops/keops/blob/improve_ci_setup/pykeops/setup.py#L84) combined with a new [`pytest.sh` script](https://github.com/getkeops/keops/blob/improve_ci_setup/pytest.sh)).

I get the following error on oban (c.f. https://ci.inria.fr/keops/blue/organizations/jenkins/KeOps_ci/detail/PR-230/10/pipeline/16):
```
  NVIDIA A10 with CUDA capability sm_86 is not compatible with the current PyTorch installation.

  The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.

  If you want to use the NVIDIA A10 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
```
Do you have any idea how to proprely install `torch` on `oban`?

**Comment by joanglaunes** [comment]
> 

Hi @gdurif ,
I don't know if this can help you, but about PyTorch, I have installed it on oban through conda with the command
`conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch`

**Comment by gdurif** [comment]
@joanglaunes Here is the solution from [pytorch page](https://pytorch.org/get-started/locally/) (and thanks to @bcharlier) with `pip` and cuda 11.3:
```
pip3 install torch==1.11.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
```

**Comment by gdurif** [comment]
Test are passing, I am merging this :smiley:

**Pull request merged**
